export const GET_CMS_ARTICLE_REQUESTED = 'GET_CMS_ARTICLE_REQUESTED' as const;
export const GET_CMS_ARTICLE_SUCCEEDED = 'GET_CMS_ARTICLE_SUCCEEDED' as const;
export const GET_CMS_ARTICLE_FAILED = 'GET_CMS_ARTICLE_FAILED' as const;
export const RESET_CMS_ARTICLE = 'RESET_CMS_ARTICLE' as const;
