export const GET_CMS_PAGE_REQUESTED = 'GET_CMS_PAGE_REQUESTED' as const;
export const GET_CMS_PAGE_SUCCEEDED = 'GET_CMS_PAGE_SUCCEEDED' as const;
export const GET_CMS_PAGE_FAILED = 'GET_CMS_PAGE_FAILED' as const;
export const RESET_CMS_PAGE = 'RESET_CMS_PAGE' as const;

export const GET_CMS_NEWS_ARTICLE_REQUESTED =
  'GET_CMS_NEWS_ARTICLE_REQUESTED' as const;
